# this file is managed by dry-rb/devtools project

name: ci

on:
  push:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run all tests
        run: echo "all good"
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    needs: tests
    env:
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{secrets.GH_PAT}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Bundle
        run: |
          bundle install
      - name: Symlink ossy
        run: |
          ln -sf "$(bundle info ossy --path)/bin/ossy" bin/ossy
      - name: Trigger release workflow
        run: |
          tag=$(echo $GITHUB_REF | cut -d / -f 3)
          bundle exec bin/ossy gh w $GITHUB_REPOSITORY release --payload "{\"tag\":\"$tag\"}"
