
name: Devtools App
on:
  repository_dispatch:
    types: [rubocop]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Run robocop
        run: echo '{"sha":"${{ github.event.client_payload.sha }}"}' > rubocop-result.json
      - name: Upload results
        uses: actions/upload-artifact@v1
        with:
          name: rubocop-result.json
          path: rubocop-result.json
